In [34]:
import numpy as np 
import pandas as pd

In [35]:
df = pd.read_csv("iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [36]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [37]:
df = df.drop("Id", axis =1 )

In [38]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [39]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['Species'] = encoder.fit_transform(df['Species'])

In [40]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [41]:
df['Species'].unique()

array([0, 1, 2])

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=5)

In [43]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
39             5.1           3.4            1.5           0.2
53             5.5           2.3            4.0           1.3
79             5.7           2.6            3.5           1.0
10             5.4           3.7            1.5           0.2
50             7.0           3.2            4.7           1.4
..             ...           ...            ...           ...
8              4.4           2.9            1.4           0.2
73             6.1           2.8            4.7           1.2
144            6.7           3.3            5.7           2.5
118            7.7           2.6            6.9           2.3
99             5.7           2.8            4.1           1.3

[120 rows x 4 columns]

In [44]:
Y_train

39     0
53     1
79     1
10     0
50     1
      ..
8      0
73     1
144    2
118    2
99     1
Name: Species, Length: 120, dtype: int64

In [45]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape 

((120, 4), (30, 4), (120,), (30,))

In [46]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(multi_class= 'multinomial', solver='lbfgs')
model.fit(X_train, Y_train)

c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial')

In [47]:
y_pred = model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix,accuracy_score

confusion_matrix(Y_test, y_pred)

array([[ 8,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 11]])

In [49]:
accuracy= accuracy_score(y_pred, Y_test)
accuracy

0.9666666666666667

In [50]:
print("Confusion matrix as a dataframe")
pd.DataFrame(confusion_matrix(Y_test, y_pred), columns = list(range(0,3)))

Confusion matrix as a dataframe


0   1   2
0  8   0   0
1  0  10   1
2  0   0  11

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [52]:
acc = accuracy_score(Y_test, y_pred)
acc

0.9666666666666667

In [53]:
ps = precision_score(Y_test, y_pred, average= None)
ps

array([1.        , 1.        , 0.91666667])

In [54]:
r = recall_score(Y_test, y_pred, average = "macro")
r


0.9696969696969697

In [55]:
f1 = f1_score(Y_test, y_pred, average= "weighted")
f1

0.9665976535541752

In [56]:
params ={
    'solver'  : ['lbfgs', 'liblinear', 'saga', 'saga'],
    'penalty' : ['l2', 'l1'],
    'multi_class' :['auto', 'ovr', 'multinomial']
}

In [57]:
from sklearn.model_selection import GridSearchCV
model = LogisticRegression()
grid = GridSearchCV(model, param_grid=params, scoring='accuracy', n_jobs=-1, cv = 5 )

In [58]:
grid.fit(X_train, Y_train)

c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
25 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\adpub\anaconda3\envs\my_ml_env\Lib\site-packages\sklearn

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'multi_class': ['auto', 'ovr', 'multinomial'],
                         'penalty': ['l2', 'l1'],
                         'solver': ['lbfgs', 'liblinear', 'saga', 'saga']},
             scoring='accuracy')

In [59]:
grid.best_params_

{'multi_class': 'auto', 'penalty': 'l2', 'solver': 'saga'}

In [60]:
grid.best_score_

np.float64(0.9916666666666668)

In [61]:
import pickle

pickle.dump(df,open('df.pkl','wb'))
pickle.dump(model,open('model.pkl','wb'))